helm/Chart.yaml
Updated app name in Chart.yaml
=> [fix] Updated app name in Chart.yaml

src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
Added receipt's timestamps and timestamp "generated_at" valorization 
[Issue PRDP-135](https://pagopa.atlassian.net/browse/PRDP-135?atlOrigin=eyJpIjoiMmVkZGM2Mzg3MDMzNDNkMmJkMjQ5NTkzY2QwYzQzZjgiLCJwIjoiaiJ9)
=> [PRDP-135] Added receipt's timestamps

.env.example, README.md, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, integration-test/src/features/receipt_pdf_datastore.feature, src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/PdfEngineClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/ReceiptBlobClientImpl.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/ReceiptQueueClientImpl.java, src/main/resources/logback.xml, src/test/java/it/gov/pagopa/receipt/pdf/generator/client/PdfEngineClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/client/ReceiptBlobClientImplTest.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/client/ReceiptQueueClientImplTest.java
- Added environment variable `WORKING_DIRECTORY_PATH` 
- Removed duplicated secret `RECEIPT_QUEUE_CONN_STRING` and `BLOB_STORAGE_CONN_STRING` and changed to `RECEIPTS_STORAGE_CONN_STRING` 
- Fixed unit test
- Fixed ids in integration tests
- Fix typo in logback.xml
Avoid function host restart
Run unit test and local execution
=> [PRDP-137] fix: Move working directory to avoid host restart

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/generator/Info.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java, src/test/resources/logback-test.xml
- Rollback commented logs
- Rollback info function
- Added logback-test.xml for unit test logs
=> Rollback commented logs and info function

helm/values-uat.yaml
- Decreased max replica in UAT chart to 1
Avoid scaling
=> feat: Decrease max replica in UAT chart

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
Removed fiscal code from pdf name used to save the pdf in Blob Storage
Remove private user information
=> [PRDP-148] Removed fiscal code from pdf name

.devops/performance-test-pipelines.yml, performance-test/docker-compose.yaml, performance-test/run_performance_test.sh, performance-test/src/dev.environment.json, performance-test/src/local.environment.json, performance-test/src/modules/common.js, performance-test/src/modules/queue_client.js, performance-test/src/receipt_generator.js, performance-test/src/uat.environment.json, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/event/DebtorPosition.java
- Added performance tests
- Added performance tests pipeline
[Issue PRDP-130](https://pagopa.atlassian.net/jira/software/c/projects/PRDP/boards/440?modal=detail&selectedIssue=PRDP-130)
=> [PRDP-130] feat: Add performance tests & pipeline

src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/CartItem.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/EventData.java
List of Changes
Updated receipt entity with notification data
=> [PRDP-104] feat: introducing cart data for notification in receipt

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: Upd mem req

src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/EventData.java
=> fix: Add missing field

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
Reworked pdf name as `<prefix>-<date yymmdd>-<eventId>-<suffix>`
[Issue PRDP-148](https://pagopa.atlassian.net/browse/PRDP-148?atlOrigin=eyJpIjoiYWQ1NzRlZmQzZGZmNDk0NWE1ZTRhMzg5MWFhZDU3YTkiLCJwIjoiaiJ9)
=> [PRDP-148] Reworked pdf name

src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/CartItem.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/EventData.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/IOMessageData.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/ReasonError.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/ReceiptMetadata.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/model/PdfGeneration.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
- Updated unit test for `GenerateReceiptPdfService` and `GenerateReceiptPdf`
- do some refactor
- fixed receipt already created check
Update unit tests
=> [PRDP-70] fix: Update unit tests

agent/config.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
- Updated config.yaml to avoid loading opentelemetry package
- Changed enviornment variable used in helm chart to include java agents, attempting to avoid classloading issue
[Issue PRDP-154](https://pagopa.atlassian.net/browse/PRDP-154?atlOrigin=eyJpIjoiN2M5Y2Y0ODViYTQ1NDU1ZmJhYzJmMmJjN2FlZjY1OTYiLCJwIjoiaiJ9)
Linkage error on opentelemetry classes caused by multiple loading instances of the same classes, changed configurations in order to avoid multiple class loading instances of the opentelemetry classes on prometheus agent
=> [PRDP-154] fix: Opentelemetry loading issue

integration-test/src/step_definitions/common.js, integration-test/src/step_definitions/receipt_pdf_generator_step.js, performance-test/src/modules/common.js
- Update receipt model in integration and performance test with the necessary field for building notification message subject and markdown
- Update biz event in integration and performance test with transaction details fields
=> [PRDP-153] fix: Update biz event and receipt in integration and performance tests

src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
Formatted date values for template generation
[Issue PRDP-168](https://pagopa.atlassian.net/browse/PRDP-168?atlOrigin=eyJpIjoiZWRkYzk2MzcxZTk1NDM4MzhjMjJhNmJkYzZiOGU1NzQiLCJwIjoiaiJ9)
Dates must be formatted as "gg month yyyy, hh:mm:ss" (es. “13 ottobre 2023, 16:46:59”)
=> [PRDP-168] feat: Format date value for template

src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
Added minimum and maximum fraction digits to currency format
Missing second decimal digits in currency value, it was displayed es. "0,4" instead of "0,40"
=> [fix-currency-format] fix: Changed currency format

src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java
- Added section in receipt to store error that occur for payer elaboration
=> [PRDP-164] feat: Added specific section for payer error in receipt

src/main/resources/psp_config_file.json
=> chore: PSP config update

helm/values-prod.yaml
=> fix: Deploy prod

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
- Updated logs
Add alert on generator errors
=> [PRDP-176] chore: Update logs for alert

.github/maven_code_review/action.yml, .github/workflows/code_review.yml, Dockerfile, host.json, pom.xml
- Migrated to java17
- Updated system-stubs-jupiter dependency
[Issue PRDP-193](https://pagopa.atlassian.net/browse/PRDP-193?atlOrigin=eyJpIjoiZTY5YjUwMWRmMGZlNDdlZjkwYzI2M2ZiM2U5ODlkMzkiLCJwIjoiaiJ9)
Run unit tests
=> [PRDP-193] Migrate to java17

helm/values-prod.yaml
- Fixed tokenizer path in prod
Tokenizer path in helm prod was wrong
expected)
=> [fix] Fixed tokenizer path in prod

src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/enumeration/ReasonErrorCode.java
- Updated & allined reason error codes
- Cleaned code
=> [fix] Updated reason error codes

host.json
=> chore: Upd host queue cfg

helm/values-prod.yaml
- Fixed error in production config regarding the poison queue
=> fix: updated values-prod.yaml

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
- Implemented regex (^[\d\s\W_]+$) for invalid names (names with only special chars es. "-- --")
- Returned null If fiscal code and fullname are equals
- Replaced all CSV special char ("," ";" ":") in fullname
- Updated unit tests
[Issue PRDP-211](https://pagopa.atlassian.net/browse/PRDP-211?atlOrigin=eyJpIjoiY2I1N2RhYWFjYWMyNGJlMTk0ZTMwMmNjYWRmOTkzY2EiLCJwIjoiaiJ9)
[Issue PRDP-217](https://pagopa.atlassian.net/browse/PRDP-217?atlOrigin=eyJpIjoiYzllMWQ4MDRhYTVhNDdkMWIxOTRhOGZkN2VkZjdkYTEiLCJwIjoiaiJ9)
Run unit tests
=> [PRDP-211] Implement Regex for invalid names

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
- Updated fullName regex and conversion on special characters
=> [PRDP-229] feat: updated fullName regexp

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
- Added cart.item.subject mapping exception
- Updated unit tests
[Issue PRDP-292](https://pagopa.atlassian.net/browse/PRDP-292?atlOrigin=eyJpIjoiMTM3MjNhYWNjYWVjNGQ1MzgyOTkyYmMwNmQzMzk4NDUiLCJwIjoiaiJ9)
The receipt was generated even when the payment object was absent
Unit test
=> [PRDP-292] Added cart.item.subject exception

.gitignore, report/src/utils/report.js
=> chore: Re-formatting daily report

.github/workflows/daily_report_receipt.yml, .identity/00_data.tf, .identity/03_github_environment.tf
=> fix: Report

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
=> fix: GenerateReceiptPdfServiceImpl

src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
=> Fix relaxed debtor checks

src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java
- Added isCart field to Receipt
[Issue PRDP-286](https://pagopa.atlassian.net/browse/PRDP-286?atlOrigin=eyJpIjoiZGM2YjAyYmU2ZjIzNDQzMGE4NWNlNGYwYTJhZGY1YjgiLCJwIjoiaiJ9)
=> [PRDP-286] Added isCart field to Receipt

.github/workflows/code_review.yml, .github/workflows/integration_test.yml, .identity/03_github_environment.tf, integration-test/src/step_definitions/aesUtils.js
- Fixed env for AES encryption in integration tests
Broken integration test
=> [fix] Fixed aes env name for github env

.github/workflows/daily_report_receipt.yml, report/src/utils/report.js
=> [PRDP-321] fix: Report

.github/workflows/daily_report_receipt.yml
=> chore: Test run report

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
- Introducing check to ensure that produced documents under the minimal file size provide a status FAILED
- Updated unit tests
https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-1029
=> [PRDP-1029] feat: updated generation to include min file checking

src/main/resources/psp_config_file.json
Modified data for the following PSP:
- IConto - modified the province
- BCC Calabria Nord - modified PSP company name
The updates has been requested by the PSPs
=> [PAGOPA-1830] fix-psp-data-iconto-and-bcc-calabria-nord

.github/workflows/deploy_with_github_runner.yml
=> feat: Self_hosted_runner_image_tag

.github/workflows/daily_report_receipt.yml
=> chore: Fix bot report

host.json, pom.xml, src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java, src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
https://learn.microsoft.com/en-us/azure/azure-functions/migrate-cosmos-db-version-3-version-4?tabs=isolated-process&pivots=programming-language-java
Azure Functions upgrade and maintenance
- Tested in local and DEV environment
=> [PAGOPA-2017] chore: Upgrade ExtensionBundle

src/main/resources/psp_config_file.json
- introduced missing psp data in config
=> [PPANTT-98] feat: Update psp_config_file.json

helm/values-prod.yaml, src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Fix wisp nav prefix
Needed in order to produce the correct pdf receipt when a wisp payment is involved
Manually and through junit tests
=> fix: Pidm 51 fix nav wisp + increase pod memory in PROD

.github/maven_code_review/action.yml, .github/workflows/integration_test.yml, .identity/.terraform.lock.hcl, .identity/99_main.tf, helm/Chart.lock
- use self-hosted-job for integration test gha execution
- bump cache gha to `v4.2.0`
Fix integration test and code review GHA
=> fix: GHA execution

.github/workflows/deploy_with_github_runner.yml, .github/workflows/release-deploy.yml, .identity/00_data.tf, .identity/03_github_environment.tf, .identity/99_main.tf, Dockerfile, helm/Chart.lock, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, host.json, pom.xml
- Implemented new runner
- Implemented workload identity with helm version 7.5.0
[PIDM-482](https://pagopa.atlassian.net/browse/PIDM-482)
[PIDM-482]: https://pagopa.atlassian.net/browse/PIDM-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [PIDM-482] Implement workload identity & new runner

helm/templates/configmaps.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java, src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
- added new local payments method name map
- updated build receipt PDF template logic to use new payments method name map
- updated unit tests
[PIDM-352](https://pagopa.atlassian.net/browse/PIDM-352)
[PIDM-352]: https://pagopa.atlassian.net/browse/PIDM-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PIDM-352] fix: Payment method name mapping

helm/templates/configmaps.yaml
- Added payment method Klarna
[PIDM-733](https://pagopa.atlassian.net/browse/PIDM-733)
[PIDM-733]: https://pagopa.atlassian.net/browse/PIDM-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [PIDM-733] Add payment method Klarna
